name: treshop
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.3+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0-nullsafety.0
  bottom_sheet: ^1.0.0
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  dots_indicator: ^2.0.0
  flutter:
    sdk: flutter
  flutter_feather_icons: ^2.0.0+1
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^0.6.0
  flutter_spinkit: ^5.0.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^0.22.0
  flutter_swiper: ^1.1.6
  fluttertoast: ^8.0.7
  form_field_validator: ^1.1.0
  get: ^4.1.4
  google_fonts: ^2.1.0
  intl: ^0.17.0
  octo_image: ^1.0.0+1
  provider: ^5.0.0
  pull_to_refresh: ^2.0.0
  readmore: ^2.0.0
  simple_animations: ^3.1.1
  smooth_star_rating:
    git:
      url: https://github.com/educup/smoothratingbar
  timeline_tile: ^2.0.0
  very_good_analysis: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
